css changes
UmangLadha/Client-site pull request #7
Opened 2022-02-04 07:35 UTC by UmangLadha

2022-02-04 07:44 UTC, aadharbhatt requested changes

2022-02-04 07:44 UTC, aadharbhatt commented on src/components/Services.js
> +                <Secondservices title="Creative Branding" />
give proper name

2022-02-05 16:53 UTC, aadharbhatt approved these changes

2022-02-05 16:54 UTC, merged

2022-02-05 17:29 UTC, UmangLadha commented
![SharedScreenshot](https://user-images.githubusercontent.com/84621610/152652208-e67e2bb2-589f-4c86-af1f-1733e4b9146f.jpg)